<h1>Index  ! Messages</h1>

<h2>Tous les messages :</h2>
<table>
    <thead>
    <th>id</th>
    <th>Name</th>
    <th>isAdmin ?</th>
    </thead>
    <tbody>
<?php foreach($this->users as $user ): ?>

   <tr>
       <td> <?= $user['id'] ?> </td>
       <td> <?= $user['name'] ?> </td>
       <td> <?= $user['isadmin'] == 0 ? 'non' : 'oui'; ?> </td>
   </tr>

<?php endforeach ?>
    </tbody>
</table>
