<h1>Index  ! Messages</h1>

<h2>Tous les messages :</h2>
<table>
    <thead>
    <th>id</th>
    <th>contenu</th>
    <th>isAdmin ?</th>
    <th>Auteur</th>
    </thead>
    <tbody>
<?php foreach($this->users as $user ): ?>

   <tr>
       <td> <?= $message['id'] ?> </td>
       <td> <?= $message['content'] ?> </td>
       <td> <?= $message['user']['isAdmin'] == 0 ? 'non' : 'oui'; ?> </td>
       <td> <?= $message['user'] ?> </td>
   </tr>

<?php endforeach ?>
    </tbody>
</table>
