<h1>Index  ! Messages</h1>

<h2>Tous les messages :</h2>

<a href="message/create">Write a message</a>

<?php foreach($this->messages as $message ): ?>

    <fieldset>
        <legend>
            by : <?= $message['user'] ?> ,  <?=  $this->dateFormat(
                $message['dateCreation'],

                IntlDateFormatter::LONG, // date
                IntlDateFormatter::MEDIUM, // time
                "fr"); ?>
        </legend>
        id : <?= $message['id'] ?> <br/>
        <?= $message['content'] ?>
    </fieldset>

    <?php if ($user = $this->identity() AND $user->getRole() == 'admin') : ?>
        <a href="message/update/<?= $message['id'] ?>">Edit this message</a>
        <?php endif ?>

    <br/><br/><br/>
<?php endforeach ?>