<h1>Index  !</h1>

<h2>Liste des utilisateurs : </h2>
<table>
    <thead>
    <th>id</th>
    <th>Name</th>
    <th>isAdmin ?</th>
    </thead>
    <tbody>
<?php foreach($this->users as $user ): ?>

   <tr>
       <td> <?= $user['id'] ?> </td>
       <td> <?= $user['userName'] ?> </td>
       <td> <?= $user['isAdmin'] == 0 ? 'non' : 'oui'; ?> </td>
   </tr>

<?php endforeach ?>
    </tbody>
</table>
